### ISSUE TITLE
[BUG]  error: implicit declaration of function 'String__iterator'; did you mean 'Vec_String__iterator'? when compiling the `std/string` usage demo

### ISSUE THREAD

**Issue by forchid** [z-libs/Zen-C#376]
**Describe the bug**
Failed to compile the [`std/string` usage demo](https://docs.zenc-lang.org/std/string/).

**To Reproduce**
# the test
```sh
lang> zc build strtest.zc -oa
   Compiling strtest.zc
In file included from a.c:7:
a.c:536:9: warning: '_stricmp' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
  536 | int32_t strcasecmp(const char* s1, const char* s2);
      |         ^~~~~~~~~~
a.c: In function 'main':
a.c:2848:20: error: implicit declaration of function 'String__iterator'; did you mean 'Vec_String__iterator'? [-Wimplicit-function-declaration]
 2848 |     ZC_AUTO __it = String__iterator(&s);
      |                    ^~~~~~~~~~~~~~~~
      |                    Vec_String__iterator
a.c:2850:25: error: request for member 'next' in something not a structure or union
 2850 |     ZC_AUTO __opt = __it.next();
      |                         ^
a.c:2851:5: error: '__opt' undeclared (first use in this function)
 2851 | if (__opt.is_none()) break;
      |     ^~~~~
a.c:2851:5: note: each undeclared identifier is reported only once for each function it appears in
a.c:2854:31: error: 'c' undeclared (first use in this function)
 2854 |     ({ fprintf(stdout, _z_str(c), _z_arg(c)); fprintf(stdout, "\n"); 0; });
      |                               ^
a.c:76:29: note: in definition of macro '_z_str'
   76 | #define _z_str(x) _Generic((x), _Bool: "%s", char: "%c", signed char: "%c", unsigned char: "%u", short: "%d", unsigned short: "%u", int: "%d", unsigned int: "%u", long: "%ld", unsigned long: "%lu", long long: "%lld", unsigned long long: "%llu", float: "%f", double: "%f", char*: "%s", const char*: "%s", void*: "%p" _z_128_map _z_objc_map)
      |                             ^
error: C compilation failed
```
# the source
```zc
import "std/string.zc"

fn main() {
    let s = String::from("Hello");

    // Append requires a pointer to another String
    let part = String::from(" World");
    s.append(&part);
    
    // Iteration (UTF-8 aware)
    for c in s {
        println "{c}";
    }

    // Use c_str() to print
    println "{s.c_str()}"; // Prints "Hello World"
    
    if (s.starts_with("Hello")) {
        // ...
    }
} // s is freed automatically here
```
**Expected behavior**
Compiling ok.

**Screenshots**
No.

**Environment (please complete the following information):**
 - OS: Windows 10 x64.
 - Zen C Version: v0.4.3, zc 7b2aa89-dirty
 - Compiler: GCC 15

**Additional context**
No.

**Comment by forchid** [comment]
It works in zc v0.4.4.
