### ISSUE TITLE
[BUG] `String Interpolation` doesn't work in `assert()` and `assert()` not dropped in the mode `--release`

### ISSUE THREAD

**Issue by forchid** [z-libs/Zen-C#402]
**Describe the bug**
`String Interpolation` doesn't work in `assert()` and `assert()` not dropped in the mode `--release` or when defining `-DNDEBUG`.

**To Reproduce**
# the test
```sh
var-const> zc -O2 def-test.zc
   Compiling def-test.zc
    Finished build in 0.21s
var-const> .\def-test
"Assertion failed: " {n} not expected, but {max_size}
var-const> zc --release def-test.zc
   Compiling def-test.zc
    Finished build in 0.18s
var-const> .\def-test
"Assertion failed: " {n} not expected, but {max_size}
```
# the source
```zc
import "std/core.zc"

fn main() {
    def max_size = 1000;
    let buf: char[max_size];
    //def max_size = 4000; // error: redefinition of 'max_size'
    
    for i in 0 .. buf.len {
        //def max_size = 0;
        buf[i] = i;
        //assert(max_size != 0)
    }
    
    let n = 1000;
    assert(max_size != n, "{n} not expected, but {max_size}")
    
    for i in 0 .. buf.len {
        let c = buf[i];
        if c != (char)i {
            panic("Unexpected value {c}");
        }
        if i % (buf.len / 10) == 0 {
            "At {i}"
        }
    }
    
    println "ok."
    //readln()
}
```

**Expected behavior**
 - The result for `String interpolation`: "Assertion failed: " 1000 not expected, but 1000.
 - When using the flag `--release` or defining `-DNDEBUG`, the "Assertion failed: ..." ignored.

**Screenshots**
No.

**Environment (please complete the following information):**
 - OS: Windows 10 x64.
 - Zen C Version:  v0.4.4, zc 5e8b9ce-dirty
 - Compiler: Mingw GCC 15.2.0.

**Additional context**
No.
