### ISSUE TITLE
[BUG] cpp mode doesn't work with zc build

### ISSUE THREAD

**Issue by 5quirre1** [z-libs/Zen-C#252]
**Describe the bug**
doing `zc build cppfile.zc --cpp` doesn't transpile to a cpp file, it transpiles to .c

**To Reproduce**
1. create a zen-c program with some c++ stuff
2. do the command above
3. outputs an error, in my case:

```ps1
out.c:98:10: fatal error: vector: No such file or directory
   98 | #include <vector>
      |          ^~~~~~~~
compilation terminated.
error: C compilation failed
```

**Expected behavior**
Should be outputting to a .cpp file and not a .c

**Screenshots**

**Environment (please complete the following information):**
- OS: Linux Mint 22.2 x86_64 (Kernel 6.17.0-14-generic)
- Zen C Version: latest
- Compiler: GCC 13

**Additional context**
nothing here

**Comment by 5quirre1** [comment]
this is super lazy but it should be pretty straight forward

**Comment by lunardoesdev** [comment]
Hello, with current main branch of Zen-C I cant reproduce your issue:|
```
satori@core ~/a [1]> zc build a.zc --cpp --verbose 
   Compiling a.zc
     Command g++ -o a.out out.cpp -lm -I. -I./std/third-party/tre/include
out.cpp:1: warning: "_GNU_SOURCE" redefined
    1 | #define _GNU_SOURCE
      | 
<command-line>: note: this is the location of the previous definition
    Finished build in 0.37s
```

**Comment by 5quirre1** [comment]
> Hello, with current main branch of Zen-C I cant reproduce your issue:|
> ```
> satori@core ~/a [1]> zc build a.zc --cpp --verbose 
>    Compiling a.zc
>      Command g++ -o a.out out.cpp -lm -I. -I./std/third-party/tre/include
> out.cpp:1: warning: "_GNU_SOURCE" redefined
>     1 | #define _GNU_SOURCE
>       | 
> <command-line>: note: this is the location of the previous definition
>     Finished build in 0.37s
> ```

Oh weird wtf?? maybe it was just like NOW fixed or smth cause it was NOT working last night LOL

**Comment by 5quirre1** [comment]
> > Hello, with current main branch of Zen-C I cant reproduce your issue:|
> > ```
> > satori@core ~/a [1]> zc build a.zc --cpp --verbose 
> >    Compiling a.zc
> >      Command g++ -o a.out out.cpp -lm -I. -I./std/third-party/tre/include
> > out.cpp:1: warning: "_GNU_SOURCE" redefined
> >     1 | #define _GNU_SOURCE
> >       | 
> > <command-line>: note: this is the location of the previous definition
> >     Finished build in 0.37s
> > ```
> 
> Oh weird wtf?? maybe it was just like NOW fixed or smth cause it was NOT working last night LOL

No, it wasn't fixed.. weird AF I'll prob reupdate and see if it fixes it ig??

**Comment by 5quirre1** [comment]
yea for some reason, it just wasn't working LMFAO, works now
