### ISSUE TITLE
[BUG] Speificying an array of unknown size in  a Struct does not work

### ISSUE THREAD

**Issue by general-rishkin** [z-libs/Zen-C#212]
**Describe the bug**
This non-generic version works:

```
struct FooBar {
  data: [int]
}

fn main() {
  let arr = [1,2,3,4,5]
  let _ = FooBar{ data: arr }
}
```
but this generic version fails:
```
struct FooBar<T> {
  data: [T]
}

fn main() {
  let arr = [1,2,3,4,5]
  let _ = FooBar{ data: arr }
}
```

**Expected behavior**
Should infer ```T``` as ```int``` and compile.

**Screenshots**
```
out.c:88:18: error: unknown type name ‘T’
   88 | struct Slice_T { T *data; int len; int cap; };
      |                  ^
out.c: In function ‘main’:
out.c:97:5: error: unknown type name ‘FooBar’
   97 |     FooBar _ = (struct FooBar){.data = arr};
      |     ^~~~~~
out.c:97:33: error: ‘struct FooBar’ has no member named ‘data’
   97 |     FooBar _ = (struct FooBar){.data = arr};
      |                                 ^~~~
out.c:97:40: warning: excess elements in struct initializer
   97 |     FooBar _ = (struct FooBar){.data = arr};
      |                                        ^~~
out.c:97:40: note: (near initialization for ‘(anonymous)’)
out.c:97:31: error: invalid use of undefined type ‘struct FooBar’
   97 |     FooBar _ = (struct FooBar){.data = arr};
      |                               ^
C compilation failed.
```

**Environment (please complete the following information):**
 - OS: Ubuntu 25.10
 - Zen C Version: v0.4.0-108-g26bc7ce
 - Compiler: GCC 15

**Comment by AiGentsy** [comment]
Hi! I noticed this issue and think I can help.

I've analyzed the problem and here's my proposed solution:

Based on my analysis, this can be resolved by addressing the core issue.

I'd be happy to submit a PR with this fix. Would that be helpful?

Best,
AiGentsy

**Comment by Zuhaitz-dev** [comment]
Solved while working on #211 

```
❯ cat issue_212.zc
struct FooBar<T> {
  data: [T]
}

fn main() {
  let arr = [1,2,3,4,5]
  let _ = FooBar{ data: arr }
}
❯ ./zc issue_212.zc
   Compiling issue_212.zc
    Finished build in 0.05s
```
